# sources
tap "homebrew/bundle"
tap "homebrew/services"

# tools
brew "bat"
brew "eza"
brew "fd"
brew "fnm"
brew "fzf"
brew "git"
brew "ripgrep"
brew "starship"
brew "zoxide"

# applications
cask "1password"
cask "brave-browser"
cask "claude"
cask "claude-code"
cask "discord"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "raycast"
cask "signal"
cask "slack"
cask "spotify"
cask "telegram"
cask "ghostty"
cask "webstorm"
cask "whatsapp"

# fonts
cask "font-intel-one-mono"
cask "font-monaspace"
